#+TITLE: Rezumate fișe disciplină anul I (2020-2021)
#+OPTIONS: toc:3

:PROPERTIES:
:UNNUMBERED: notoc
:END:
* Cuprins
:PROPERTIES:
:TOC:      :include all :depth 2 :ignore this
:END:
:CONTENTS:
- [[#semestrul-i][Semestrul I]]
  - [[#analiză-matematică][Analiză matematică]]
  - [[#baze-de-date][Baze de date]]
  - [[#fundamentele-programării][Fundamentele programării]]
  - [[#interfețe-om-calculator][Interfețe om-calculator]]
  - [[#medii-și-instrumente-de-programare][Medii și instrumente de programare]]
- [[#semestrul-ii][Semestrul II]]
  - [[#algoritmi-fundamentali][Algoritmi fundamentali]]
  - [[#arhitectura-sistemelor-de-calcul][Arhitectura sistemelor de calcul]]
  - [[#fundamentele-algebrei][Fundamentele algebrei]]
  - [[#geometrie-computațională][Geometrie computațională]]
  - [[#programare-orientată-obiect][Programare orientată-obiect]]
  - [[#structuri-de-date][Structuri de date]]
:END:


* Semestrul I
** Analiză matematică
*** Disciplina
Analiză matematică/Mathematical analysis

*** Statutul disciplinei
Obligatoriu

*** Precondiții
-

*** Conținutul disciplinei
**** Introducere
Obiectul de studiu al calculului diferențial și integral. Mulţimea numerelor
reale - reprezentare zecimală, axioma Cantor-Dedekind. Ecuații și inecuații cu
modul. Funcții elementare.

**** Capitolul I: Şiruri şi serii de numere reale

Mulţimea numerelor reale. Şiruri de numere reale: limita unui şir, şir
convergent, şir fundamental. Dreapta reală încheiată. Serii numerice -
condiţii necesare, condiţii suficiente de convergenţă. Operaţii cu
serii. Criterii de convergenţă pentru serii cu termeni pozitivi. Criteriul
rădăcinii, criteriul raportului. Serii de puteri.

**** Capitolul II: Funcţii de mai multe variabile. Limite şi continuitate

Spaţiul euclidian R^n - produs scalar, normă şi distanţă. Şiruri de vectori
din R^n. Funcţii vectoriale de o variabilă reală.  Limite şi continuitate
pentru funcţii de n variabile. Limita după o direcţie, limite iterate.

**** Capitolul III: Funcții diferențiabile
Derivate parţiale (într-un punct şi pe o mulţime). Derivata după o
direcţie. Operatori diferenţiali în teoria cîmpurilor: gradient, divergenţă,
rotor. Matrice jacobiană, determinant funcţional. Derivate parţiale de ordin
superior. Diferenţiala unei funcţii de mai multe variabile. Aplicaţii ale
diferenţialei în calculul cu aproximări. Diferenţierea şi derivarea funcţiilor
compuse. Derivate parțiale și diferenţiale de ordin superior.

**** Capitolul IV: Formula lui Taylor. Extreme locale ale funcţiilor de mai multe variabile

Formula lui Taylor pentru funcţii de una sau mai multe variabile. Aplicaţii în
determinarea extremelor locale ale funcţiilor de mai multe variabile. Teorema
lui Fermat pentru funcţii de mai multe variabile. Studiul punctelor de extrem
cu ajutorul diferenţialei a doua.

**** Capitolul V: Integrarea funcţiilor de o variabilă

Primitive. Integrala Riemann, Integrale improprii de speţa I şi de speţa a
doua. Studiul convergenţei integralelor improprii.

**** Capitolul VI: Integrale curbilinii

Curbe plane şi în spaţiu. Ecuaţii parametrice. Element de arc. Integrala
curbilinie de speţa I. Definiţie, aplicaţii, Integrala curbilinie de speţa a
doua. Lucru mecanic, Independenţa de drum a integralelor curbilinii de speţa a
doua

*** Bibliografia minimală obligatorie
- Miron Nicolescu, Nicolae Dinculeanu şi Solomon Marcus - /Analiză
  matematică/, vol. 1, Editura Didactică şi Pedagogică, Bucureşti, Ediţia IV (1971) sau Ediţia V (1981).
- M. Mocanu, /Matematici aplicate 1 (Analiză matematică)/, Editura Alma Mater,
  Bacău, 2007.
- I. Crăciun - /[[http://www.mec.tuiasi.ro/diverse/analiza_matematica_calcul_diferential.pdf][Analiză matematică. Calcul diferenţial]]/, Universitatea Tehnică
  “Gh. Asachi”, Iaşi, 2011
- I. Crăciun - /[[http://www.mec.tuiasi.ro/diverse/analiza_matematica_calcul_integral.pdf][Analiză matematică. Calcul integral]]/, Editura PIM, Iaşi, 2007
- S. Chiriţă - /[[https://www.academia.edu/19535189/78351889-Probleme-de-Matematici-Superioare-Stan-Chirita][Probleme de matematici superioare]]/, Editura Didactică şi
  Pedagogică, Bucureşti, 1989

*** Fond de timp alocat pe forme de activitate
- Semestrul: 1
- Forme de activitate/număr de ore:
  - Curs: 2 x 14 = 28
  - Seminar: 2 x 14 = 28
  - Laborator: -
  - Proiect: -
- Număr de credite: 6

*** Procedura de evaluare a cunoștințelor
Examen

*** Evaluare pe parcurs
Temă de casă
** TODO Baze de date
*** Disciplina
*** Statutul disciplinei
*** Precondiții
*** Conținutul disciplinei
*** Bibliografia minimă obligatorie
*** Fond de timp alocat pe forme de activitate
*** Procedura de evaluare a cunoștințelor
*** Evaluare pe parcurs
** Fundamentele programării
*** Disciplina
Fundamentele programării/ Fundamentals of programming

*** Statutul disciplinei
Obligatoriu

*** Precondiții
-

*** Conținutul disciplinei
**** Capitolul 1: Introducere
Paradigme ale programării. Exemplificări.
**** Capitolul 2: Algoritmi
Etapele rezolvării unei probleme, Definiţia algoritmului,
Caracteristicile algoritmilor. Reprezentări.
**** Capitolul 3: Date
 Constante şi variabile. Expresii, Tipuri de date simple, Tipuri de
 date structurate.
**** Capitolul 4: Elementele programării structurate
 Structurile de bază, auxiliare. Teorema programării structurate,
 Instrucţiunea de atribuire. Operaţii de intrare şi ieşire,
 Implementarea structurilor de control, Exemple de algoritmi,
 Complexitatea algoritmilor
**** Capitolul 5: Vectori și înregistrări
 Definire vectori/structuri ca tip de date. Citire, afişare, exemple.
 Sortare, interclasare
**** Capitolul 6: Pointeri și referințe
 Tipul pointer. Tipul referinţă. Noţiunea de variabilă dinamică. Liste
**** Capitolul 7: Subprograme
 Definirea subprogramelor, Circuitul datelor între subprograme
**** Capitolul 8: Recursivitate
 Prezentare generală, Funcţii recursive, Proceduri recursive, Metoda
Divide- et-impera, Probleme ale căror rezolvări se pot defini în
termeni recursivi
**** Capitolul 9: Șiruri de caractere
 Prelucrări. Exemple de aplicaţii.
**** Capitolul 10: Fișiere
 Tipuri de fisiere. Operatii cu fisiere. Aplicatii.
**** Capitolul 11: Probleme recapitulative
Aplicaţii diverse cu caracter recapitulativ al materiei de curs 
*** Bibliografia minimală obligatorie
- Bogdan Pătruţ, /Aplicaţii în C şi C++/, Editura Teora, Bucureşti, 1998
- B. Kernigham, D. Ritchie - /Limbajul de programare C/, Ed. Teora, orice ediție
- E. Nechita, G. C. Crişan, I.M. Furdu, /Îndrumar de laborator C/C++/, regim intern, disponibil
la http://www.infoifr.ub.ro (se va solicita parola)
- Furdu I. – /Programare procedurală/ - note de curs, draft, disponibil la http://www.infoifr.ub.ro
(se va solicita parola)
*** Fond de timp alocat pe forme de activitate
- Semestrul: 1
- Forme de activitate/număr de ore:
  - Curs: 2 x 14 = 28
  - Seminar: -
  - Laborator: 2 x 14 = 28
  - Proiect: -
- Număr de credite: 6

*** Procedura de evaluare a cunoștințelor
Examen
** TODO Interfețe om-calculator
*** Disciplina
*** Statutul disciplinei
*** Precondiții
*** Conținutul disciplinei
*** Bibliografia minimă obligatorie
*** Fond de timp alocat pe forme de activitate
*** Procedura de evaluare a cunoștințelor
*** Evaluare pe parcurs
** Medii și instrumente de programare
*** Disciplina
Medii și instrumente de programare/Software development tools and environments

*** Statutul disciplinei
Obligatoriu

*** Precondiții
-

*** Conținutul disciplinei
**** Capitolul 1: Introducere
Care este obiectul de studiu al disciplinei /Medii de programare/ și ce loc
ocupă aceasta în cadrul disciplinelor informatice. Mediul de programare Gambas:
Arhitectura mediului de programare, IDE-ul, Schema și componente suplimentare. O
duzina de întrebări la care căutam răspuns cînd învățăm un limbaj de programare.

**** Capitolul 2. Date simple 
Constante şi variabile. Expresii - ce sînt şi la ce folosesc, cum se formează
expresiile, sintaxa expresiilor. Tipuri de date simple - cum se reprezintă
diferite date în calculator. Operații cu tipurile de date simple. Tipuri de date
speciale: timp și data calendaristică. Era Gambas. Tipuri de date de uz general:
Tipul =Variant=. Controalele sînt simultan și date, controale din mediul Gambas,
structura și obiect descrise într-un fișier =class=. Alte tipuri de date tratate
ca tipuri simple. Tendințe și direcții de dezvoltare a mediilor vizuale și
limbajelor acestora.

**** Capitolul 3. Date structurate I: Vectori și matrice, liste sau colecții
Tipuri de date structurate - noţiunea de tablou, matrice, notația cu [] la
vectori. Tipuri de date structurate - noţiunea de listă sau colecție,
notația cu [] la liste, Liste de elemente, liste de controale, operații
asupra listelor, construirea dinamică a unei liste, procesarea iterativă sau
recursivă a listelor, reprezentarea prin desen a listelor.

**** Capitolul 4: Date structurate II: Structuri, obiecte, clasă, imagine
Tipuri de date structurate - noţiunea de structură, record, obiect, clasă. Cum
devine programul un fisier class, adică o clasă. Crearea dinamică a elementelor
unui vector de controale (obiecte) în Gambas cu =New=. Diferente Gambas/Visual
Basic în materie de folosire a matricelor Controale care conțin o imagine.
PictureBox și folosirea sa. Inițializare cu diverse formate de imagine,
utilizare. Extensii de fișiere imagine.

**** Capitolul 5: Elementele programării structurate
Cod cu structură nerepetitivă: structura liniară, cu exemple. Cod cu
structura nerepetitivă: structurile alternative, =If= și respectiv
=Select=, cu exemple. Structurile repetitive. Condiționare anterioară
sau posterioară, diferențe între concepte, exemple.  Structurile
auxiliare: structura =With= pentru acces la cîmpuri/atribute,
funcții/metode. Structurile auxiliare: structura =For Each= pentru
parcurgere de liste și colecții. Instrucţiunea de atribuire. Operaţii
de intrare şi iesire - semantică, utilizare. Variații de sintaxă a
structurilor de control - cum se descriu elementele programării
structurate în cazul unor limbaje de programare diferite.  Exemple de
algoritmi - se vor proiecta algoritmi pentru calcule simple
matematice, financiar-contabile, dar şi algoritmi mai complecşi de
căutare, sortare etc.
**** Capitolul 6: Subprograme
Programarea structurată tradițională, conceptul de
funcție/procedură/metodă care necesita execuție de cod, rolul
subprogramelor în acest context. Programarea vizuală bazată pe
evenimente, conceptul de eveniment care necesita execuție de cod,
rolul subprogramelor în acest context. Definirea subprogramelor -
procedurile, (sub)rutinele, funcţiile - şi cum se declară şi se
definesc ele în cadrul unui program; exemplificări în diferite limbaje
de programare. Circuitul datelor între subprograme - cum se apelează
subprogramele, modalităţi de transmitere a parametrilor, apel prin
valoare, apel prin referința, apel prin nume, =ByRef= și respectiv
=ByVal=. Atenție: Evenimentul =Change()= și propagarea modificarilor.
**** Capitolul 7: Noțiunile de bază ale programării vizuale
Consideraţii generale - ce este programarea vizuală şi prin ce se
deosebeşte de alte paradigme. Forme - ce sînt formele. Controale şi
proprietăţile lor - ce sînt controalele şi cum se proiectează
interfaţa unei aplicaţii vizuale. Evenimente - ce sînt evenimentele, ce
evenimente pot apărea asupra diferitelor controale şi cum pot fi ele
folosite. Legarea evenimentelor de controale - cum se realizează
legătura între controale şi diferitele evenimente ce pot avea loc
asupra lor; scrierea codului subrutinelor şi realizarea programului.
Proprietăţi/Atribute şi metode - ce sînt acestea şi cum se folosesc.
Resurse suplimentare folosite de programe
**** Capitolele 8-11: Exemple de programare în mediul vizual
***** Partea I
Pornirea mediului de programare vizual. Calcule cu date în consolă.
Primul tău program. Un salut special pentru tine! =Message.Info=, alte
mesaje. Un calculator cu operaţii aritmetice în Visual Basic/Un
calculator cu operatii aritmetice și =SpinBox=-uri în
Gambas. =ListBox=, liste şi modificarea listelor.
***** Partea II
Utilizarea instrucțiunilor =Case= și =If=. Procesarea evenimentului
=Change()=.  Cadre (Frame-uri) și RadioButoane. Exemplul cu opțiunea
fumatorului.  Jocul BatalieNumerica – Studiu de caz. (versiuni
succesive în dezvoltare).  =ProgressBar= – ghidat prin
program. =ProgressBar= – ghidat de timere.  Controale din setul Qt:
=Slider=, =Dial=, =LCDNumber=, etc.  =TabStrip=. Interfețe cu tab-uri.
***** Partea III
Vector de controale, grup de butoane, eveniment atașat de grup,
Tooltip, (inclusiv =With=), Entitatea/Obiectul Last – ultimul control
acționat.  Căutare în =ListBox= cu algoritm explicit sau metoda
existența Colectii. Colecții de PictureBox-uri. Timere.  CheckBox-uri
și colectarea opțiunilor bifate într-o colecție indexabilă.  Alocare
dinamica cu =New= a unor obiecte.  Funcții și subrutine. Transferul
rezultatelor prin valoare respectiv prin referință.
***** Partea IV
Obiecte agregate sau cînd structurile au în interior alte date
structurate sau alte obiecte. Exemplu cu JackPot-ul. Aflarea
coordonatelor mouse-ului. Experiment pentru a compara transferul prin
referinta și transferul prin valoare.  Fișiere: Open, Handle, Print,
Input. Scrierea în fisiere text, Citirea din fisiere text.  Vectori de
structuri utilizator sau de obiecte. Ex. cu palatul. Acces la
elementele vectorului de structuri/obiecte.  Initializari cu subrutina
=_new()=. Maniera POO de inițializare.  Un joc cu imagini şi
cronometre. Grafice. Fişiere text - să salvam şi să restauram datele

**** Capitolul 12: Conceptele programării orientate pe obiecte
Introducere - o iniţiere intuitivă în teoria programării orientate pe
obiecte, cu exemplificări din lumea reală. Definirea claselor - cum se
definesc clasele, cîmpuri şi metode, cîmpuri private şi publice;
exemplificări în diferite limbaje de programare obiectuală, Static.
Derivare - realizarea derivării unei clase din alta clasă, moştenirea
atributelor și metodelor. Agregarea obiectelor. Implementări: Problema
clientului de la CEC. Jocul Jackpot
*** Bibliografia minimală obligatorie
- /Microsoft Visual Basic 6.0 Ghidul programatorului/, Ed.Teora, 1998
- John W. Rittinghouse, /[[http://distro.ibiblio.org/vectorlinux/Uelsk8s/GAMBAS/gambas-beginner-guide.pdf][A Beginner's Guide to Gambas]]/, e-book, 2005
- B. Pătruţ, /Aplicaţii în VB/, Teora, 2000
- Daniel Campos, Jose Luis Redrejo, /[[https://openlibra.com/es/book/gambas-programacion-visual-con-software-libre][Gambas – Programacion visual cons
  Software Libre]]/, e-book, 2009
- Gambas, site-uri: http://gambas.sourceforge.net/en/main.html, http://gambaswiki.org/wiki
- Ubuntu Linux > 16.04, Fedora Linux > 25 sau altă distribuție de Linux recentă
*** Fond de timp alocat pe forme de activitate
- Semestrul: 1
- Forme de activitate/număr de ore:
  - Curs: 2 x 14 = 28
  - Seminar: -
  - Laborator: 2 x 14 = 28
  - Proiect: -
- Număr de credite: 6

*** Procedura de evaluare a cunoștințelor
Examen


* Semestrul II
** TODO Algoritmi fundamentali
*** Disciplina
*** Statutul disciplinei
*** Precondiții
*** Conținutul disciplinei
*** Bibliografia minimă obligatorie
*** Fond de timp alocat pe forme de activitate
*** Procedura de evaluare a cunoștințelor
*** Evaluare pe parcurs
** TODO Arhitectura sistemelor de calcul
*** Disciplina
*** Statutul disciplinei
*** Precondiții
*** Conținutul disciplinei
*** Bibliografia minimă obligatorie
*** Fond de timp alocat pe forme de activitate
*** Procedura de evaluare a cunoștințelor
*** Evaluare pe parcurs
** TODO Fundamentele algebrei
*** Disciplina
*** Statutul disciplinei
*** Precondiții
*** Conținutul disciplinei
*** Bibliografia minimă obligatorie
*** Fond de timp alocat pe forme de activitate
*** Procedura de evaluare a cunoștințelor
*** Evaluare pe parcurs
** TODO Geometrie computațională
*** Disciplina
*** Statutul disciplinei
*** Precondiții
*** Conținutul disciplinei
*** Bibliografia minimă obligatorie
*** Fond de timp alocat pe forme de activitate
*** Procedura de evaluare a cunoștințelor
*** Evaluare pe parcurs
** TODO Programare orientată-obiect
*** Disciplina
*** Statutul disciplinei
*** Precondiții
*** Conținutul disciplinei
*** Bibliografia minimă obligatorie
*** Fond de timp alocat pe forme de activitate
*** Procedura de evaluare a cunoștințelor
*** Evaluare pe parcurs
** TODO Structuri de date
*** Disciplina
*** Statutul disciplinei
*** Precondiții
*** Conținutul disciplinei
*** Bibliografia minimă obligatorie
*** Fond de timp alocat pe forme de activitate
*** Procedura de evaluare a cunoștințelor
*** Evaluare pe parcurs
