* Disciplina
Metode avansate de programare/ Advanced programming methods

* Statutul disciplinei
Opțional

* Precondiții
-

* Conținutul disciplinei
** Algoritmii si eficiența lor.
Ce este un algoritm. Probleme si cazuri. Eficienta algoritmilor. Cazul
mediu si cel mai nefavorabil. Ce este o operaţie elementara. De ce
avem nevoie de algoritmi eficienţi? Analiza algoritmilor eficienţi
** Metoda Greedy.
O problema prototip. Tipul de probleme la care se aplica metoda
Greedy. Mecanism general. Probleme ilustrative. Complexitatea
algoritmilor Greedy
** Metoda Backtracking.
Doua exemple prototip. Tipul de probleme la care se aplica metoda
Backtracking. Mecanism general. Probleme ilustrative Complexitatea
algoritmilor Backtracking. Backtracking generalizat (in
plan). Backtracking recursiv. Variante ale metodei Backtracking
** Metoda programării dinamice.
Exemplu prototip. Tipul de probleme la care se aplica metoda
programării dinamice. Mecanism general. Probleme
ilustrative. Compararea metodei programării dinamice cu metoda Greedy.
Complexitatea metodei programării dinamice
** Metoda Divide et impera.
Exemplu prototip. Tipul de probleme la care se aplica metoda Divide et
impera. Mecanism general. Probleme ilustrative Complexitatea metodei
Divide et impera
** Metoda Branch and bound.
Exemplu prototip. Arborele spaţiului de soluţii. Complexitatea
algoritmilor Branch and bound. Complexitatea metodei Divide et impera
** Metode euristice.
Descrierea generala. Exemple Algoritmi probabilistici. O problema
prototip. Caracteristicile algoritmilor probabilistici. Clasificarea
algoritmilor probabilistici. Algoritmii Monte Carlo. Algoritmii Las
Vegas. Algoritmii Sherwood. Concluzii
* Bibliografia minimală obligatorie
- Octavian Aspru, /Tehnici de programare/, Editura Adias, Rm. Vîlcea, 1997
- Leon Livovschi, Horia Georgescu, /Sinteza si analiza algoritmilor/, Bucureşti
- Bogdan Pătruţ, /Algorithm Design Paradigms/, AVM, München, 2011
* Fond de timp alocat pe forme de activitate
- Semestrul: 1
- Forme de activitate/număr de ore:
  - Curs: 1 x 14 = 14
  - Seminar: -
  - Laborator: 1 x 14 = 14
  - Proiect: -
- Număr de credite: 5
* Procedura de evaluare a cunoștințelor
Examen
