* Disciplina
Redactare și comunicare științifică și profesională/Scientific and professional writing and communication

* Statutul disciplinei
Opțional

* Precondiții
-

* Conținutul disciplinei
1. Comunicarea, limbajul, principii ale comunicării verbale: claritatea, simplitatea, corectitudinea. Matricea comunicării științifice.
2. Materialul ştiinţific. Etape şi procedura generală de elaborare. Caracteristici ale unei lucrări ştiinţifice. Scop şi beneficii. Necesitate şi dificultate.
3. Documentare. Tipuri de documente (articole, cărţi, monografii, documente electronice, baze de date şi aplicaţii). Etape şi faze. Specificul documentării în domeniul Matematică.
4. Documentare. Baze de date online, free trial, cu acces deschis. Depozite digitale instituţionale. Reviste online cu acces deschis. Căutare avansată, utilitare de căutare.
5. Structura generală a unui material ştiinţific. Premise şi condiţii (originalitate, elementeobligatorii în concordanţă cu reglementările naţionale şi/sau intenaţionale şi specifice).
6. Tehnoredactarea materialului ştiinţific: cerinţe de scriere şi predare a lucrărilor. Declaraţia de autenticitate. Diseminarea rezultatelor ştiinţifice
7. Elemente de etică şi deontologie. Plagiatul
* Bibliografia minimală obligatorie
1. American Psychological Association, Publication Manual of the American Psychological Association (5th ed.). Washington, DC, 2001, http://www.apa.org/ethics/code/92-02codecompare.pdf
2. Andronescu, Şerban C., /Tehnica scrierii academice/, Bucureşti, Editura Fundaţiei „Romînia de mâine”, 1977
3. Eco, Umberto, /Cum se face o teză de licenţă/, Editura Pontica, 2000
* Fond de timp alocat pe forme de activitate
- Semestrul: 1
- Forme de activitate/număr de ore:
  - Curs: 1 x 14 = 14
  - Seminar: -
  - Laborator: -
  - Proiect: -
- Număr de credite: 1

* Procedura de evaluare a cunoștințelor
Examen
