* Disciplina
Tehnici avansate de programare/Advanced programming techniques

* Statutul disciplinei
Obligatoriu

* Precondiții
-

* Conținutul disciplinei
** Complexitatea algoritmilor
Algoritm, complexitatea algoritmului, clase de complexitate, notaţii
** Probleme de sortare şi căutare
Necesitatea sortării şi a căutării. Metode eficiente pentru sortare şi căutare. Tehnici complexe,
bazate pe arbori şi dicţionare.
** Probleme de teoria codurilor
Metode de codificare, coduri fundamentale, clasificare, utilizarea codurilor
** Probleme de criptologie
Criptografia şi criptanaliza. Tipuri de cifruri, algoritmi moderni de criptografie
** Probleme de optimizare
Complexitatea problemelor actuale de optimizare, metode exacte, metode aproximative şi
metode euristice de rezolvare
** Probleme de teoria jocurilor
Noţiunea de joc, clasificare, strategii de rezolvare, echilibru, echilibru Nash, exemple de jocuri
* Bibliografia minimală obligatorie
- T. H. Cormen, C. E. Leierson, R. L. Rivest, C. Stein, /Introduction to Algorithms/, MIT
Press, 2009
- D. Knuth, /Arta programării calculatoarelor/, Teora, 2000
- D. Hrinciuc Logofătu, /Probleme rezolvate şi algoritmi/, Polirom, 2001
- V. Iorga, E. Kalisz, C. Țăpuş, /Concursuri de programare. Probleme şi soluţii/, Teora, 1997
* Fond de timp alocat pe forme de activitate
- Semestrul: 1
- Forme de activitate/număr de ore:
  - Curs: 2 x 14 = 28
  - Seminar: 1 x 14 = 14
  - Laborator: 1 x 14 = 14
  - Proiect: -
- Număr de credite: 6

* Procedura de evaluare a cunoștințelor
Examen
