* Disciplina
Baze de date/Databases

* Statutul disciplinei
Obligatoriu

* Precondiții
-
* Conținutul disciplinei
** Capitolul 1: Introducere
Definiţii. Proprietăţi. Exemple. Schemele: externă, conceptuală,
internă. Proiectarea bazelor de date. Baze de date
relaţionale. Chei. Reguli de integritate a datelor. Modelarea logică a
datelor.  Vederile utilizatorilor. Construirea unei vederi
utilizator. Integrarea vederilor utilizatorilor.
** Capitolul 2: Algebra relațională
Operatori peste mulţimi. Operatori specifici. Utilizarea algebrei relaţionale.
** Capitolul 3: Modelul entitate-relație
Concepte fundamentale şi avansate. Transformarea modelului E-R în
model relaţional
** Capitolul 4: Normalizarea relațiilor
Dependențe funcţionale. Dependenţe multivaloare. Dependenţe
joncţiune. Forme normale.  Normalizarea relaţiilor.
** Capitolul 5: Tranzacții
Definire. Proprietăţi. Stările unei tranzacţii. Utilizarea
tranzacţiilor la reconstituirea conţinutului bazei de date. Utilizarea
tranzacţiilor în rezolvarea problemelor accesului concurent la date.
Utilizarea mărcilor de timp.
** Capitolul 6: Baze de date distribuite
Definiţii. Arhitecturi.
** Capitolul 7: Data mining, Big Data, NoSQL
Gestionarea colecţiilor moderne de date

* Bibliografia minimală obligatorie
- Octavian Bîscă, /Baze de date/, Ed. All, Bucureşti, 1997
- Pavel Năstase şi colectiv, /Microsoft Access/, Ed. Teora, Bucureşti, 2000
- Gh. Popa, Al. Ştefănescu, V. Stanciu, V. Ivancenco, V. Ţintă, /Sisteme de gestiune a bazelor de date : dBase IV, Oracle/, Ed. All, Bucureşti, 1998
- I. Lungu, C. Bodea, G. Bădescu, C. Ioniţă, /Baze de date. Organizare, proiectare şi implementare/, Ed. All, Bucureşti, 1995
* Fond de timp alocat pe forme de activitate
- Semestrul: 1
- Forme de activitate/număr de ore:
  - Curs: 2 x 14 = 28
  - Seminar: -
  - Laborator: 2 x 14 = 28
  - Proiect: -
- Număr de credite: 5

* Procedura de evaluare a cunoștințelor
Examen

